 CREATE TABLE TC_OBK_FILE
   (	
	"TC_OBK01" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"TC_OBK02" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"TC_OBK03" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"TC_OBK04" VARCHAR2(4 BYTE), 
	"TC_OBKACTI" VARCHAR2(1 BYTE), 
	"TC_OBKDATE" DATE, 
	"TC_OBKGRUP" VARCHAR2(10 BYTE), 
	"TC_OBKUSER" VARCHAR2(10 BYTE), 
	"TC_OBKMODU" VARCHAR2(10 BYTE), 
	"TC_OBKORIG" VARCHAR2(10 BYTE), 
	"TC_OBKORIU" VARCHAR2(10 BYTE), 
	 CONSTRAINT "TPC_TC_OBK_PK" PRIMARY KEY ("TC_OBK01", "TC_OBK02", "TC_OBK03")
   )