SELECT
  COMPANY           
, CREATOR           
, USR_GROUP         
, CREATE_DATE       
, MODIFIER          
, MODI_DATE         
, FLAG              
, CUSTOMER          
, PRODUCT           
, REGION            
, DEALER            
, YK001             
, YK002             
, YK003             
, YK004             
, YK005             
, YK006             
, YK007             
, YK008             
, YK009             
, YK010             
, SALYK01           
, SALYK02           
, SALYK03           
, SALYK04           
, SALYK05           
, SALYK06           
, SALYK07           
, SALYK08           
, SALYK09           
, SALYK10           
, SALYK11           
, SALYK12           
, SALYK13           
, SALYK14           
, SALYK15           
, SALYK16           
, SALYK17           
, SALYK18           
, SALYK19           
, SALYK20           
, YK011             
, YK012             
, YK013             
, YK014             
FROM SALYK