SELECT
  COMPANY           
, CREATOR           
, USR_GROUP         
, CREATE_DATE       
, MODIFIER          
, MODI_DATE         
, FLAG              
, CUSTOMER          
, PRODUCT           
, REGION            
, DEALER            
, YH001             
, YH002             
, YH003             
, YH004             
, YH005             
, YH006             
, YH007             
, YH008             
, SALYH01           
, SALYH02           
, SALYH03           
, SALYH04           
, SALYH05           
, SALYH06           
, SALYH07           
, SALYH08           
, SALYH09           
, SALYH10           
, SALYH11           
, SALYH12           
, SALYH13           
, SALYH14           
, SALYH15           
, SALYH16           
, SALYH17           
, SALYH18           
, SALYH19           
, SALYH20           
, YH009             
FROM SALYH