SELECT
  COMPANY           
, CREATOR           
, USR_GROUP         
, CREATE_DATE       
, MODIFIER          
, MODI_DATE         
, FLAG              
, CUSTOMER          
, PRODUCT           
, REGION            
, DEALER            
, YB001             
, YB002             
, YB003             
, YB004             
, YB005             
, YB006             
, YB007             
, YB008             
, YB009             
, SALYB01           
, SALYB02           
, SALYB03           
, SALYB04           
, SALYB05           
, SALYB06           
, SALYB07           
, SALYB08           
, SALYB09           
, SALYB10           
, SALYB11           
, SALYB12           
, SALYB13           
, SALYB14           
, SALYB15           
, SALYB16           
, SALYB17           
, SALYB18           
, SALYB19           
, SALYB20           
, YB010             
, YB011             
, YB012             
, YB013             
, YB014             
, YB015             
, YB016             
, YB017             
, YB018             
, YB019             
FROM SALYB