SELECT
  COMPANY           
, CREATOR           
, USR_GROUP         
, CREATE_DATE       
, MODIFIER          
, MODI_DATE         
, FLAG              
, CUSTOMER          
, PRODUCT           
, REGION            
, DEALER            
, YA001             
, YA002             
, YA003             
, YA004             
, YA005             
, YA006             
, YA007             
, CRMYA01           
, CRMYA02           
, CRMYA03           
, CRMYA04           
, CRMYA05           
, CRMYA06           
, CRMYA07           
, CRMYA08           
, CRMYA09           
, CRMYA10           
, CRMYA11           
, CRMYA12           
, CRMYA13           
, CRMYA14           
, CRMYA15           
, CRMYA16           
, CRMYA17           
, CRMYA18           
, CRMYA19           
, CRMYA20           
, YA008             
, YA009             
, YA010             
, YA011             
, YA012             
, YA013             
, YA014             
, YA015             
, YA016             
, YA017             
, YA018             
, YA019             
, YA020             
, YA021             
, YA022             
FROM CRMYA