SELECT
  BMA01             
, BMA02             
, BMA03             
, BMA04             
, BMA05             
, BMAUSER           
, BMAGRUP           
, BMAMODU           
, BMADATE           
, BMAACTI           
, BMA06             
, BMA07             
, BMAICD01          
, BMA08             
, BMA09             
, BMA10             
, BMAUD01           
, BMAUD02           
, BMAUD03           
, BMAUD04           
, BMAUD05           
, BMAUD06           
, BMAUD07           
, BMAUD08           
, BMAUD09           
, BMAUD10           
, BMAUD11           
, BMAUD12           
, BMAUD13           
, BMAUD14           
, BMAUD15           
, BMAORIU           
, BMAORIG           
, TA_BMA01          
, TA_BMA02          
, TA_BMA03          
, TA_BMA04          
FROM BMA_FILE