SELECT
  COMPANY           
, CREATOR          
, USR_GROUP        
, CREATE_DATE      
, MODIFIER         
, MODI_DATE        
, FLAG             
, CUSTOMER         
, PRODUCT          
, REGION           
, DEALER           
, YA001            
, YA002            
, YA003            
, WARYA01          
, WARYA02          
, WARYA03          
, WARYA04          
, WARYA05          
, WARYA06          
, WARYA07          
, WARYA08          
, WARYA09          
, WARYA10          
, WARYA11          
, WARYA12          
, WARYA13          
, WARYA14          
, WARYA15          
, WARYA16          
, WARYA17          
, WARYA18          
, WARYA19          
, WARYA20          
, YA004            
FROM WARYA