SELECT
  COMPANY           
, CREATOR           
, USR_GROUP         
, CREATE_DATE       
, MODIFIER          
, MODI_DATE         
, FLAG              
, CUSTOMER          
, PRODUCT           
, REGION            
, DEALER            
, ZT001             
, ZT002             
, ZT003             
, ZT004             
, ZT005             
, ZT006             
, ZT007             
, ZT008             
, ZT009             
, SALZT01           
, SALZT02           
, SALZT03           
, SALZT04           
, SALZT05           
, SALZT06           
, SALZT07           
, SALZT08           
, SALZT09           
, SALZT10           
, SALZT11           
, SALZT12           
, SALZT13           
, SALZT14           
, SALZT15           
, SALZT16           
, SALZT17           
, SALZT18           
, SALZT19           
, SALZT20           
FROM SALZT