SELECT
  COMPANY           
, CREATOR           
, USR_GROUP         
, CREATE_DATE       
, MODIFIER          
, MODI_DATE         
, FLAG              
, CUSTOMER          
, PRODUCT           
, REGION            
, DEALER            
, YI001             
, YI002             
, YI003             
, YI004             
, YI005             
, YI006             
, YI007             
, YI008             
, YI009             
, YI010             
, SALYI01           
, SALYI02           
, SALYI03           
, SALYI04           
, SALYI05           
, SALYI06           
, SALYI07           
, SALYI08           
, SALYI09           
, SALYI10           
, SALYI11           
, SALYI12           
, SALYI13           
, SALYI14           
, SALYI15           
, SALYI16           
, SALYI17           
, SALYI18           
, SALYI19           
, SALYI20           
, YI011             
, YI012             
, YI013             
, YI014             
FROM SALYI