SELECT
  COMPANY           
, CREATOR           
, USR_GROUP         
, CREATE_DATE       
, MODIFIER          
, MODI_DATE         
, FLAG              
, CUSTOMER          
, PRODUCT           
, REGION            
, DEALER            
, YD001             
, YD002             
, YD003             
, YD004             
, YD005             
, YD006             
, YD007             
, YD008             
, YD009             
, YD010             
, YD011             
, YD012             
, YD013             
, CRMYD01           
, CRMYD02           
, CRMYD03           
, CRMYD04           
, CRMYD05           
, CRMYD06           
, CRMYD07           
, CRMYD08           
, CRMYD09           
, CRMYD10           
, CRMYD11           
, CRMYD12           
, CRMYD13           
, CRMYD14           
, CRMYD15           
, CRMYD16           
, CRMYD17           
, CRMYD18           
, CRMYD19           
, CRMYD20           
FROM CRMYD