SELECT
  COMPANY           
, CREATOR           
, USR_GROUP         
, CREATE_DATE       
, MODIFIER          
, MODI_DATE         
, FLAG              
, GA001             
, GA002             
, GA003             
, GA004             
, GA005             
, CUSTOMER          
, PRODUCT           
, REGION            
, DEALER            
, GA006             
, GA007             
, GA008             
, CRMGA01           
, CRMGA02           
, CRMGA03           
, CRMGA04           
, CRMGA05           
, CRMGA06           
, CRMGA07           
, CRMGA08           
, CRMGA09           
, CRMGA10           
, CRMGA11           
, CRMGA12           
, CRMGA13           
, CRMGA14           
, CRMGA15           
, CRMGA16           
, CRMGA17           
, CRMGA18           
, CRMGA19           
, CRMGA20           
, GA009             
, GA200             
FROM CRMGA