SELECT
  COMPANY           
, CREATOR           
, USR_GROUP         
, CREATE_DATE       
, MODIFIER          
, MODI_DATE         
, FLAG              
, ME001             PRIMARY KEY
, ME002             
, ME003             
, ME004             
, CUSTOMER          
, PRODUCT           
, REGION            
, DEALER            
, ME005             
, ME006             
, ME007             
, ME008             
, PORME01           
, PORME02           
, PORME03           
, PORME04           
, PORME05           
, PORME06           
, PORME07           
, PORME08           
, PORME09           
, PORME10           
, PORME11           
, PORME12           
, PORME13           
, PORME14           
, PORME15           
, PORME16           
, PORME17           
, PORME18           
, PORME19           
, PORME20           
, ME300             
, ME301             
, ME302             
, ME303             
, ME009             
FROM PORME