SELECT
  COMPANY           
, CREATOR           
, USR_GROUP         
, CREATE_DATE       
, MODIFIER          
, MODI_DATE         
, FLAG              
, CUSTOMER          
, PRODUCT           
, REGION            
, DEALER            
, ZD001             
, ZD002             
, ZD003             
, ZD004             
, ZD005             
, ZD006             
, ZD007             
, ZD008             
, ZD009             
, ZD010             
, SALZD01           
, SALZD02           
, SALZD03           
, SALZD04           
, SALZD05           
, SALZD06           
, SALZD07           
, SALZD08           
, SALZD09           
, SALZD10           
, SALZD11           
, SALZD12           
, SALZD13           
, SALZD14           
, SALZD15           
, SALZD16           
, SALZD17           
, SALZD18           
, SALZD19           
, SALZD20           
, ZD011             
FROM SALZD