SELECT
  COMPANY           
, CREATOR           
, USR_GROUP         
, CREATE_DATE       
, MODIFIER          
, MODI_DATE         
, FLAG              
, CUSTOMER          
, PRODUCT           
, REGION            
, DEALER            
, YO001             
, YO002             
, YO003             
, YO004             
, YO005             
, YO006             
, YO007             
, YO008             
, YO009             
, YO010             
, SALYO01           
, SALYO02           
, SALYO03           
, SALYO04           
, SALYO05           
, SALYO06           
, SALYO07           
, SALYO08           
, SALYO09           
, SALYO10           
, SALYO11           
, SALYO12           
, SALYO13           
, SALYO14           
, SALYO15           
, SALYO16           
, SALYO17           
, SALYO18           
, SALYO19           
, SALYO20           
, YO011             
, YO012             
, YO013             
, YO014             
FROM SALYO