SELECT
  COMPANY           
, CREATOR           
, USR_GROUP         
, CREATE_DATE       
, MODIFIER          
, MODI_DATE         
, FLAG              
, CUSTOMER          
, PRODUCT           
, REGION            
, DEALER            
, YC001             
, YC002             
, YC003             
, YC004             
, YC005             
, YC006             
, YC007             
, YC008             
, YC009             
, YC010             
, CRMYC01           
, CRMYC02           
, CRMYC03           
, CRMYC04           
, CRMYC05           
, CRMYC06           
, CRMYC07           
, CRMYC08           
, CRMYC09           
, CRMYC10           
, CRMYC11           
, CRMYC12           
, CRMYC13           
, CRMYC14           
, CRMYC15           
, CRMYC16           
, CRMYC17           
, CRMYC18           
, CRMYC19           
, CRMYC20           
FROM CRMYC