SELECT
  COMPANY           
, CREATOR           
, USR_GROUP         
, CREATE_DATE       
, MODIFIER          
, MODI_DATE         
, FLAG              
, CUSTOMER          
, PRODUCT           
, REGION            
, DEALER            
, ZQ001             
, ZQ002             
, ZQ003             
, ZQ004             
, ZQ005             
, ZQ006             
, ZQ007             
, SALZQ01           
, SALZQ02           
, SALZQ03           
, SALZQ04           
, SALZQ05           
, SALZQ06           
, SALZQ07           
, SALZQ08           
, SALZQ09           
, SALZQ10           
, SALZQ11           
, SALZQ12           
, SALZQ13           
, SALZQ14           
, SALZQ15           
, SALZQ16           
, SALZQ17           
, SALZQ18           
, SALZQ19           
, SALZQ20           
FROM SALZQ