SELECT
  COMPANY           
, CREATOR           
, USR_GROUP         
, CREATE_DATE       
, MODIFIER          
, MODI_DATE         
, FLAG              
, CUSTOMER          
, PRODUCT           
, REGION            
, DEALER            
, ZC001             
, ZC002             
, ZC003             
, ZC004             
, ZC005             
, ZC006             
, ZC007             
, ZC008             
, ZC009             
, ZC010             
, SALZC01           
, SALZC02           
, SALZC03           
, SALZC04           
, SALZC05           
, SALZC06           
, SALZC07           
, SALZC08           
, SALZC09           
, SALZC10           
, SALZC11           
, SALZC12           
, SALZC13           
, SALZC14           
, SALZC15           
, SALZC16           
, SALZC17           
, SALZC18           
, SALZC19           
, SALZC20           
FROM SALZC