SELECT
  COMPANY           
, CREATOR          
, USR_GROUP        
, CREATE_DATE      
, MODIFIER         
, MODI_DATE        
, FLAG             
, CUSTOMER         
, PRODUCT          
, REGION           
, DEALER           
, YM001            
, YM002            
, YM003            
, YM004            
, YM005            
, SALYM01          
, SALYM02          
, SALYM03          
, SALYM04          
, SALYM05          
, SALYM06          
, SALYM07          
, SALYM08          
, SALYM09          
, SALYM10          
, SALYM11          
, SALYM12          
, SALYM13          
, SALYM14          
, SALYM15          
, SALYM16          
, SALYM17          
, SALYM18          
, SALYM19          
, SALYM20          
FROM SALYM